# Generated by Django 4.2.7 on 2024-10-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='product_line',
            new_name='production_line',
        ),
    ]
